# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
import numpy as np
a=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [16]:
a=np.array([[1,2,3],[4,5,6]])
np.vstack(a)

array([[1, 2, 3],
       [4, 5, 6]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [17]:
a=np.array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
np.hstack(a)

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [33]:
a=np.array([[0,1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18,19]])
print('\n',a,'\n')
print(a.ravel())
print(a.flatten())


 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [35]:
a=np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [38]:
a=np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11],[12, 13, 14]])
np.vstack(a)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [43]:
a=np.random.normal((5,5))
print(a,'\n')
print(np.sqrt(a))

[4.87655991 4.51923198] 

[2.20829344 2.12584853]


## Question:8

### Create 5x6 an array and find the mean?

In [47]:
a=np.random.gamma((5,6))
print(a)
print('\n',a.mean())

[3.49798218 2.74362551]

 3.120803842971556


## Question:9

### Find the standard deviation of the previous array in Q8?

In [49]:
np.std(a)

0.3771783377656537

## Question:10

### Find the median of the previous array in Q8?

In [50]:
np.median(a)

3.120803842971556

## Question:11

### Find the transpose of the previous array in Q8?

In [51]:
np.transpose(a)

array([3.49798218, 2.74362551])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [98]:
a=np.arange(16).reshape(4,4)
print(a)
print('Sum =',np.trace(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sum = 30


## Question:13

### Find the determinant of the previous array in Q12?

In [99]:
print(np.linalg.det(a))
print(np.linalg.det([[1,2],[3,4]]))

0.0
-2.0000000000000004


## Question:14

### Find the 5th and 95th percentile of an array?

In [104]:
print(a)
print('\n',np.percentile(a,5))
print(np.percentile(a,95))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 0.75
14.25


## Question:15

### How to find if a given array has any null values?

In [109]:
print(a)
print('\n',np.isnan(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 [[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
